name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e ./server/gti
          pip install -e ./server/scc
          pip install -e ./server/secops
          pip install -e ./server/secops-soar

      - name: Check Python syntax and imports
        run: python tests/check_imports.py

      - name: Run tests
        run: |
          pytest tests/
